version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/et-ai-concierge"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/et-ai-concierge"
    schedule:
      interval: "weekly"
